### ISSUE TITLE
Alfred 5 Support?

### ISSUE THREAD

**Issue by JGStyle** [obstschale/NSC#12]
Unfortunately, this amazing workflow doesn't work for me

When I type for example "binary" in the Alfred command line, the preview looks fine:
<img width="1193" alt="Bildschirmfoto 2022-10-31 um 18 26 27" src="https://user-images.githubusercontent.com/51161233/199070837-f74c4556-ac28-4db3-b28a-09f55f95e1dc.png">

but as soon as I enter arguments, the preview vanishes and I only get the default results:
<img width="1329" alt="Bildschirmfoto 2022-10-31 um 18 26 33" src="https://user-images.githubusercontent.com/51161233/199071021-89bb6259-60d9-4001-89d4-2265fd86bf04.png">

Does this workflow work with Alfred 5?

**Comment by obstschale** [comment]
I don't use it anymore myself. Hence I did not notice that it does not work with Alfred 5.

I will give it a look

**Comment by zqzten** [comment]
This is not caused by Alfred, but by the removal of python2 since macOS 12.3. It would be grateful if this workflow can be adapted to work with python3 or we have to find a way to setup a python2 env to run it.

**Comment by tevenfeng** [comment]
Looks like that Alfred5 has deprecated XML as the format of feedback string, so we should use json instead.

Tested and resolved by #13 
![image](https://user-images.githubusercontent.com/3694248/204768022-59435632-8817-47b1-a40a-31bdc23c1b1e.png)
![image](https://user-images.githubusercontent.com/3694248/204768087-a6399bef-ef72-40ad-819a-2d117f79fcf9.png)
![image](https://user-images.githubusercontent.com/3694248/204767963-74dc57eb-9e62-44ba-9f00-b4659ce3bd12.png)

**Comment by JGStyle** [comment]
I tested the Code from the PR and works now. Thanks @tevenfeng

**Comment by llity** [comment]
> #13
There an error .

`[21:48:59.304] NSC[Script Filter] Queuing argument '1'
[21:48:59.386] NSC[Script Filter] Script with argv '(null)' finished
[21:48:59.388] NSC[Script Filter] /bin/bash: python: command not found
[21:48:59.388] ERROR: NSC[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:`
