### ISSUE TITLE
Add version to info.plist

### ISSUE THREAD

**Issue by bbezanson** [obstschale/NSC#5]
I didn't think such a simple change was worth forking and pushing and pulling :-)

The version should be the following 2 lines:
`<key>version</key>`
`<string>2.3</string>`

Added before these lines near the end of the file:
`<key>webaddress</key>`
`<string>http://hanshelgebuerger.de</string>`

**Comment by bbezanson** [comment]
If you would like me to make the change, please let me know and I'll fork it and push the change and submit the pull request.

**Comment by obstschale** [comment]
Hey thanks. Can you explain why these lines are needed or why they are important? 

I would appreciate it if you can send a PR. :)
