### ISSUE TITLE
Can not install v2.4

### ISSUE THREAD

**Issue by Isaac0616** [obstschale/NSC#7]
I can install v2.3 by double click on it but fail at v2.4.
Can someone check whether v2.4 is built correctly?
My Alfred version is V3.3.1.

**Comment by obstschale** [comment]
Thx for reporting. I will check that.

**Comment by obstschale** [comment]
I created a new build. Please download v2.4 again. :)

**Comment by Isaac0616** [comment]
I can install now. 
Thanks for the great workflow and the rapid response.
