### ISSUE TITLE
Feature request: ASCII support

### ISSUE THREAD

**Issue by dmdque** [obstschale/NSC#8]

**Comment by obstschale** [comment]
Hey @dmdque, what do you mean with ASCII support? Can you give some information about your feature request?

**Comment by dmdque** [comment]
Ah sorry, I meant support for conversion from * (decimal, hex, etc.) to ASCII and back.

This plugin is really useful for decoding data, which is sometimes some representation of ASCII.

**Comment by obstschale** [comment]
Do you mean conversion from Number to ASCII Symbol? Like `0` would output ASCII `48`?

**Comment by dmdque** [comment]
ascii A

Should output 65 for dec, 41 for hex, etc.

**Comment by obstschale** [comment]
Ok I see what you mean. However, I don't think it suites the workflow. NSC is for number systems and ASCII is not a number system but a character set. 

So actually I'm tempted to drop this feature.
